// Code generated by github.com/jt05610/scaf, DO NOT EDIT.
// Author: Jonathan Taylor
// Date: 07 Jun 2023

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: v1/housework.proto

package housework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_housework_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_v1_housework_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_v1_housework_proto_rawDescGZIP(), []int{0}
}

type Chore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Complete    bool   `protobuf:"varint,2,opt,name=complete,proto3" json:"complete,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Chore) Reset() {
	*x = Chore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_housework_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chore) ProtoMessage() {}

func (x *Chore) ProtoReflect() protoreflect.Message {
	mi := &file_v1_housework_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chore.ProtoReflect.Descriptor instead.
func (*Chore) Descriptor() ([]byte, []int) {
	return file_v1_housework_proto_rawDescGZIP(), []int{1}
}

func (x *Chore) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Chore) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *Chore) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetChoreInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetChoreInput) Reset() {
	*x = GetChoreInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_housework_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChoreInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChoreInput) ProtoMessage() {}

func (x *GetChoreInput) ProtoReflect() protoreflect.Message {
	mi := &file_v1_housework_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChoreInput.ProtoReflect.Descriptor instead.
func (*GetChoreInput) Descriptor() ([]byte, []int) {
	return file_v1_housework_proto_rawDescGZIP(), []int{2}
}

func (x *GetChoreInput) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ChoreInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Complete    bool   `protobuf:"varint,1,opt,name=complete,proto3" json:"complete,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ChoreInput) Reset() {
	*x = ChoreInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_housework_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChoreInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChoreInput) ProtoMessage() {}

func (x *ChoreInput) ProtoReflect() protoreflect.Message {
	mi := &file_v1_housework_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChoreInput.ProtoReflect.Descriptor instead.
func (*ChoreInput) Descriptor() ([]byte, []int) {
	return file_v1_housework_proto_rawDescGZIP(), []int{3}
}

func (x *ChoreInput) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *ChoreInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Chores struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chores []*Chore `protobuf:"bytes,1,rep,name=chores,proto3" json:"chores,omitempty"`
}

func (x *Chores) Reset() {
	*x = Chores{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_housework_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chores) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chores) ProtoMessage() {}

func (x *Chores) ProtoReflect() protoreflect.Message {
	mi := &file_v1_housework_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chores.ProtoReflect.Descriptor instead.
func (*Chores) Descriptor() ([]byte, []int) {
	return file_v1_housework_proto_rawDescGZIP(), []int{4}
}

func (x *Chores) GetChores() []*Chore {
	if x != nil {
		return x.Chores
	}
	return nil
}

type AddInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chores []*ChoreInput `protobuf:"bytes,1,rep,name=chores,proto3" json:"chores,omitempty"`
}

func (x *AddInput) Reset() {
	*x = AddInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_housework_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInput) ProtoMessage() {}

func (x *AddInput) ProtoReflect() protoreflect.Message {
	mi := &file_v1_housework_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInput.ProtoReflect.Descriptor instead.
func (*AddInput) Descriptor() ([]byte, []int) {
	return file_v1_housework_proto_rawDescGZIP(), []int{5}
}

func (x *AddInput) GetChores() []*ChoreInput {
	if x != nil {
		return x.Chores
	}
	return nil
}

type AddPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddPayload) Reset() {
	*x = AddPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_housework_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPayload) ProtoMessage() {}

func (x *AddPayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_housework_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPayload.ProtoReflect.Descriptor instead.
func (*AddPayload) Descriptor() ([]byte, []int) {
	return file_v1_housework_proto_rawDescGZIP(), []int{6}
}

func (x *AddPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CompleteInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChoreNumber int32 `protobuf:"varint,1,opt,name=choreNumber,proto3" json:"choreNumber,omitempty"`
}

func (x *CompleteInput) Reset() {
	*x = CompleteInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_housework_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteInput) ProtoMessage() {}

func (x *CompleteInput) ProtoReflect() protoreflect.Message {
	mi := &file_v1_housework_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteInput.ProtoReflect.Descriptor instead.
func (*CompleteInput) Descriptor() ([]byte, []int) {
	return file_v1_housework_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteInput) GetChoreNumber() int32 {
	if x != nil {
		return x.ChoreNumber
	}
	return 0
}

type CompletePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CompletePayload) Reset() {
	*x = CompletePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_housework_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletePayload) ProtoMessage() {}

func (x *CompletePayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_housework_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletePayload.ProtoReflect.Descriptor instead.
func (*CompletePayload) Descriptor() ([]byte, []int) {
	return file_v1_housework_proto_rawDescGZIP(), []int{8}
}

func (x *CompletePayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_housework_proto protoreflect.FileDescriptor

var file_v1_housework_proto_rawDesc = []byte{
	0x0a, 0x12, 0x76, 0x31, 0x2f, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x55, 0x0a, 0x05, 0x43, 0x68, 0x6f, 0x72,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x1f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x68, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x4a, 0x0a, 0x0a, 0x43, 0x68, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x32, 0x0a, 0x06,
	0x43, 0x68, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f,
	0x72, 0x6b, 0x2e, 0x43, 0x68, 0x6f, 0x72, 0x65, 0x52, 0x06, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x73,
	0x22, 0x39, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x2d, 0x0a, 0x06,
	0x63, 0x68, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x43, 0x68, 0x6f, 0x72, 0x65, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x52, 0x06, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x26, 0x0a, 0x0a, 0x41,
	0x64, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x31, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x6f, 0x72, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2b, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0xe0, 0x01, 0x0a, 0x09, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72,
	0x6b, 0x12, 0x31, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x13, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x15, 0x2e,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x40, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x18, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1a, 0x2e, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x31, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x18, 0x2e,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x6f,
	0x72, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x10, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77,
	0x6f, 0x72, 0x6b, 0x2e, 0x43, 0x68, 0x6f, 0x72, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x10, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e,
	0x43, 0x68, 0x6f, 0x72, 0x65, 0x73, 0x42, 0x18, 0x5a, 0x16, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77,
	0x6f, 0x72, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_housework_proto_rawDescOnce sync.Once
	file_v1_housework_proto_rawDescData = file_v1_housework_proto_rawDesc
)

func file_v1_housework_proto_rawDescGZIP() []byte {
	file_v1_housework_proto_rawDescOnce.Do(func() {
		file_v1_housework_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_housework_proto_rawDescData)
	})
	return file_v1_housework_proto_rawDescData
}

var file_v1_housework_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_v1_housework_proto_goTypes = []interface{}{
	(*Empty)(nil),           // 0: housework.Empty
	(*Chore)(nil),           // 1: housework.Chore
	(*GetChoreInput)(nil),   // 2: housework.GetChoreInput
	(*ChoreInput)(nil),      // 3: housework.ChoreInput
	(*Chores)(nil),          // 4: housework.Chores
	(*AddInput)(nil),        // 5: housework.AddInput
	(*AddPayload)(nil),      // 6: housework.AddPayload
	(*CompleteInput)(nil),   // 7: housework.CompleteInput
	(*CompletePayload)(nil), // 8: housework.CompletePayload
}
var file_v1_housework_proto_depIdxs = []int32{
	1, // 0: housework.Chores.chores:type_name -> housework.Chore
	3, // 1: housework.AddInput.chores:type_name -> housework.ChoreInput
	5, // 2: housework.Housework.Add:input_type -> housework.AddInput
	7, // 3: housework.Housework.Complete:input_type -> housework.CompleteInput
	2, // 4: housework.Housework.Get:input_type -> housework.GetChoreInput
	0, // 5: housework.Housework.List:input_type -> housework.Empty
	6, // 6: housework.Housework.Add:output_type -> housework.AddPayload
	8, // 7: housework.Housework.Complete:output_type -> housework.CompletePayload
	1, // 8: housework.Housework.Get:output_type -> housework.Chore
	4, // 9: housework.Housework.List:output_type -> housework.Chores
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_housework_proto_init() }
func file_v1_housework_proto_init() {
	if File_v1_housework_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_housework_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_housework_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_housework_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChoreInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_housework_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChoreInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_housework_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chores); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_housework_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_housework_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_housework_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_housework_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompletePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_housework_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_housework_proto_goTypes,
		DependencyIndexes: file_v1_housework_proto_depIdxs,
		MessageInfos:      file_v1_housework_proto_msgTypes,
	}.Build()
	File_v1_housework_proto = out.File
	file_v1_housework_proto_rawDesc = nil
	file_v1_housework_proto_goTypes = nil
	file_v1_housework_proto_depIdxs = nil
}
