// Code generated by github.com/jt05610/scaf, DO NOT EDIT.
// Author: Jonathan Taylor
// Date: 07 Jun 2023

package graph

//go:generate go run github.com/99designs/gqlgen generate
import "housework/v1"

type Resolver struct {
	housework housework.HouseworkClient
}
