// Code generated by github.com/jt05610/scaf, DO NOT EDIT.
// Author: Jonathan Taylor
// Date: 07 Jun 2023

package graph

import (
	"context"
	"housework/v1"
	"strconv"
)

// Add is the resolver for the Add field.
func (r *mutationResolver) Add(ctx context.Context, input *housework.AddInput) (*housework.AddPayload, error) {

	return r.housework.Add(ctx, input)
}

// Complete is the resolver for the Complete field.
func (r *mutationResolver) Complete(ctx context.Context, input *housework.CompleteInput) (*housework.CompletePayload, error) {

	return r.housework.Complete(ctx, input)
}

// Chore is the resolver for the Chore field.
func (r *queryResolver) Chore(ctx context.Context, id string) (*housework.Chore, error) {
	iId, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}
	return r.housework.Get(ctx, &housework.GetChoreInput{Id: int64(iId)})
}

// Chores is the resolver for the Chores field.
func (r *queryResolver) Chores(ctx context.Context) ([]*housework.Chore, error) {
	c, err := r.housework.List(ctx, nil)
	if err != nil {
		return nil, err
	}
	return c.Chores, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
