// Code generated by github.com/jt05610/scaf, DO NOT EDIT.
// Author: Jonathan Taylor
// Date: 07 Jun 2023

//go:build tools
// +build tools

package tools

import (
	_ "github.com/99designs/gqlgen"
	_ "github.com/99designs/gqlgen/graphql/introspection"
)